spring.application.name=SistemaEstoque
spring.datasource.url=jdbc:sqlite:C:/estoque/banco/estoque.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.thymeleaf.cache=false

spring.mvc.view.prefix=/templates/
spring.mvc.view.suffix=.html